# config.py

WORLD_WIDTH = 800
WORLD_HEIGHT = 600

INITIAL_POPULATION = 100
INITIAL_FOOD = 200

STARTING_ENERGY = 100.0
STARTING_HEALTH = 100.0

MAX_AGE = 1000

RANDOM_SEED = 42

# energy_loss = METABOLISM_COST_MULTIPLIER * organism.genome.metabolism
METABOLISM_COST_MULTIPLIER = 2.0

SIMULATION_TICKS = 10
